services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    # env.sh の内容。
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: isuride
      MYSQL_USER: isucon
      MYSQL_PASSWORD: isucon
    ports:
      - "3306:3306"
    volumes:
      - ./webapp/sql:/docker-entrypoint-initdb.d:ro
    command: --default-authentication-plugin=mysql_native_password
